In [86]:
import pandas as pd

In [87]:
dataset_path="E:\\BongoDev\\Python-Programming\\health_monitor_data.csv"

In [88]:
df=pd.read_csv(dataset_path)

In [89]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories      Type
0        60  '2020/12/01'    110       130     409.1      Easy
1        60  '2020/12/02'    117       145     479.0  Moderate
2        60  '2020/12/03'    103       135     340.0  Moderate
3        45  '2020/12/04'    109       175     282.4  Moderate
4        45  '2020/12/05'    117       148     406.0     Heavy

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      33 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [91]:
"""
 Data Sanitization/Cleaning

 Challenge: Contains missing values

 Approach 1: Removing the rows contains missing values
 Approach 2: Impute the missing values with statistical information/ contextual information

"""
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
Type        0
dtype: int64

In [92]:
mask=df.isnull().any(axis=1)
df[mask]

    Duration          Date  Pulse  Maxpulse  Calories      Type
18        45  '2020/12/18'     90       112       NaN  Moderate
22        45           NaN    100       119     282.0  Moderate
28        60  '2020/12/28'    103       132       NaN     Heavy

In [93]:
avg_calorie=df['Calories'].mean()

In [94]:
df['Calories']=df['Calories'].fillna(avg_calorie)
df[mask]

    Duration          Date  Pulse  Maxpulse   Calories      Type
18        45  '2020/12/18'     90       112  302.93871  Moderate
22        45           NaN    100       119  282.00000  Moderate
28        60  '2020/12/28'    103       132  302.93871     Heavy

In [95]:
# For dropping
mask=df.isnull().any(axis=1)
~mask

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
dtype: bool

In [96]:
df=df[~mask]
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
Type        0
dtype: int64

In [97]:
"""
Remove Duplicates
"""
mask=df.duplicated()
df[mask]

    Duration          Date  Pulse  Maxpulse  Calories   Type
32        60  '2020/12/12'    100       120     250.7  Heavy

In [98]:
df=df[~mask]
df.duplicated().sum()

np.int64(0)

In [99]:
"""
Another method : Drop the duplicate rows using drop_duplicates()
inplace=true : to make changes on the main data frame rather than copying
df=df.drop_duplicates(inplace=True)
""";

In [100]:
"""
Standard data format
"""
df.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [101]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
Type            str
dtype: object

In [102]:
df['Date']=df['Date'].astype('datetime64[ns]')

In [103]:
df.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: datetime64[ns](1), float64(1), int64(3), str(1)
memory usage: 1.7 KB

In [104]:
df['Type'].value_counts()

Type
Moderate    14
Heavy       13
Easy         4
Name: count, dtype: int64

In [105]:
"""
Remove Outliers
IQR - Interquartile Range

COls=[1,4,2,3,1,2,100]
L,R = Expected Data values lies in the range
<L, R> == Outliers

IQR=Q3-Q1 (75%-25%)
L=Q1-1.5*IQR
R=Q3+1.5*IQR

Any values outside the L and R are outliers
"""

df.describe()

,Duration,Date,Pulse,Maxpulse,Calories
count,31.000000,31,31.000000,31.000000,31.000000
mean,69.193548,2020-12-15 16:15:29.032258048,103.612903,128.806452,305.299272
min,30.000000,2020-12-01 00:00:00,90.000000,101.000000,195.100000
25%,60.000000,2020-12-08 12:00:00,100.000000,120.000000,250.700000
50%,60.000000,2020-12-15 00:00:00,103.000000,128.000000,300.000000
75%,60.000000,2020-12-23 12:00:00,107.000000,132.500000,342.650000
max,450.000000,2020-12-31 00:00:00,130.000000,175.000000,479.000000
std,71.064487,NaN,7.935899,13.095596,64.760652

In [106]:
Q1=df['Pulse'].quantile(0.25)
Q3=df['Pulse'].quantile(0.75)
IQR=Q3-Q1
print(IQR)
L=Q1-1.5*IQR
R=Q3+1.5*IQR
print(L,R)

7.0
89.5 117.5

In [107]:
mask_outlier=df['Pulse'].between(L,R)
df[~mask_outlier]

    Duration       Date  Pulse  Maxpulse  Calories   Type
23        60 2020-12-23    130       101     300.0  Heavy

In [108]:
df=df[mask_outlier]

In [109]:
df.info()

<class 'pandas.DataFrame'>
Index: 30 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  30 non-null     int64
 1   Date      30 non-null     datetime64[ns]
 2   Pulse     30 non-null     int64
 3   Maxpulse  30 non-null     int64
 4   Calories  30 non-null     float64
 5   Type      30 non-null     str
dtypes: datetime64[ns](1), float64(1), int64(3), str(1)
memory usage: 1.6 KB

In [110]:
"""
Exploratory Data Analysis -- Statistical Information
"""

'\nExploratory Data Analysis -- Statistical Information\n'

In [111]:
df.describe()

         Duration                 Date       Pulse    Maxpulse    Calories
count   30.000000                   30   30.000000   30.000000   30.000000
mean    69.500000  2020-12-15 10:24:00  102.733333  129.733333  305.475914
min     30.000000  2020-12-01 00:00:00   90.000000  112.000000  195.100000
25%     60.000000  2020-12-08 06:00:00  100.000000  120.750000  250.700000
50%     60.000000  2020-12-14 12:00:00  102.500000  128.500000  300.000000
75%     60.000000  2020-12-23 06:00:00  105.750000  132.750000  343.975000
max    450.000000  2020-12-31 00:00:00  117.000000  175.000000  479.000000
std     72.258516                  NaN    6.351396   12.241629   65.860156

In [112]:
"""
Col A,B,C (Target)

Correlation displays the relation between two variables
-Positive Correlation: if x increases, y increases and vice versa
-Negative Correlation: if x increases,y decreases and vice versa

Strength of correlation: [-1.1]
col A and col B correlation value is 1  ( Strongly positively correlated )
col A and col B correlation value is -1  ( Strongly negatively correlated )
col A and col B correlation value is 0  (No correlation)

"""

'\nCol A,B,C (Target)\n\nCorrelation displays the relation between two variables\n-Positive Correlation: if x increases, y increases and vice versa\n-Negative Correlation: if x increases,y decreases and vice versa\n\nStrength of correlation: [-1.1]\ncol A and col B correlation value is 1  ( Strongly positively correlated )\ncol A and col B correlation value is -1  ( Strongly negatively correlated )\ncol A and col B correlation value is 0  (No correlation)\n\n'

In [113]:
"""
Predictive analysis
- Normalizing ( Numerical Columns)
"""
def normalize(col):
    mean=col.mean()
    std=col.std()
    return (col-mean)/std

df['Pulse']=df['Pulse'].agg(normalize)
df['Maxpulse']=df['Maxpulse'].agg(normalize)
df['Duration']=df['Duration'].agg(normalize)
df['Calories']=df['Calories'].agg(normalize)

In [114]:
df.head()

   Duration       Date     Pulse  Maxpulse  Calories      Type
0 -0.131472 2020-12-01  1.144105  0.021784  1.573396      Easy
1 -0.131472 2020-12-02  2.246225  1.247111  2.634735  Moderate
2 -0.131472 2020-12-03  0.041986  0.430226  0.524203  Moderate
3 -0.339060 2020-12-04  0.986660  3.697765 -0.350377  Moderate
4 -0.339060 2020-12-05  2.246225  1.492176  1.526326     Heavy

In [115]:
"""
Categorical Columns
Encoding:
- One hot Encoding
- Label EnCoding
"""

df['Type'].value_counts()

Type
Moderate    14
Heavy       12
Easy         4
Name: count, dtype: int64

In [117]:
# Label Encoding
df['Type']=pd.Categorical(
    df['Type'],
    categories=['Easy','Moderate','Heavy'],
    ordered=True
).codes
df.head()

   Duration       Date     Pulse  Maxpulse  Calories  Type
0 -0.131472 2020-12-01  1.144105  0.021784  1.573396     0
1 -0.131472 2020-12-02  2.246225  1.247111  2.634735     1
2 -0.131472 2020-12-03  0.041986  0.430226  0.524203     1
3 -0.339060 2020-12-04  0.986660  3.697765 -0.350377     1
4 -0.339060 2020-12-05  2.246225  1.492176  1.526326     2