In [22]:
import pandas as pd

In [23]:
dataset_path="E:\\BongoDev\\Python-Programming\\health_monitor_data.csv"

In [24]:
df=pd.read_csv(dataset_path)

In [25]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories      Type
0        60  '2020/12/01'    110       130     409.1      Easy
1        60  '2020/12/02'    117       145     479.0  Moderate
2        60  '2020/12/03'    103       135     340.0  Moderate
3        45  '2020/12/04'    109       175     282.4  Moderate
4        45  '2020/12/05'    117       148     406.0     Heavy

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      33 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [27]:
"""
 Data Sanitization/Cleaning

 Challenge: Contains missing values

 Approach 1: Removing the rows contains missing values
 Approach 2: Impute the missing values with statistical information/ contextual information

"""
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
Type        0
dtype: int64

In [28]:
mask=df.isnull().any(axis=1)
df[mask]

    Duration          Date  Pulse  Maxpulse  Calories      Type
18        45  '2020/12/18'     90       112       NaN  Moderate
22        45           NaN    100       119     282.0  Moderate
28        60  '2020/12/28'    103       132       NaN     Heavy

In [29]:
avg_calorie=df['Calories'].mean()

In [30]:
df['Calories']=df['Calories'].fillna(avg_calorie)
df[mask]

    Duration          Date  Pulse  Maxpulse   Calories      Type
18        45  '2020/12/18'     90       112  302.93871  Moderate
22        45           NaN    100       119  282.00000  Moderate
28        60  '2020/12/28'    103       132  302.93871     Heavy

In [31]:
# For dropping
mask=df.isnull().any(axis=1)
~mask

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22    False
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
dtype: bool

In [33]:
df=df[~mask]
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
Type        0
dtype: int64

In [40]:
"""
Remove Duplicates
"""
mask=df.duplicated()
df[mask]

    Duration          Date  Pulse  Maxpulse  Calories   Type
32        60  '2020/12/12'    100       120     250.7  Heavy

In [41]:
df=df[~mask]
df.duplicated().sum()

np.int64(0)

In [ ]:
# Another method : Drop the duplicate rows using drop_duplicates()
# implace=true : to make changes on the main data frame rather than copying
df=df.drop_duplicates(inplace=True)

In [42]:
"""
Standard data format
"""
df.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [47]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
Type            str
dtype: object

In [48]:
df['Date']=df['Date'].astype('datetime64[ns]')

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: datetime64[ns](1), float64(1), int64(3), str(1)
memory usage: 1.7 KB

In [50]:
df['Type'].value_counts()

Type
Moderate    14
Heavy       13
Easy         4
Name: count, dtype: int64

In [ ]:
"""
Remove Outliers

"""