In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
"""
 Pandas Dataframe : A data structure for tabular data
"""
health_data_table={
    "height":[5.5,5.5,'A',5.8],
    "weight":[57,62,72,75],
    "bmi":[19.3,12.7,20.3,None],
    'smoker':['Yes','no',None,'Yes']
}

In [4]:
health_data_table.keys()

dict_keys(['height', 'weight', 'bmi', 'smoker'])

In [5]:
health_data_table.values()

dict_values([[5.5, 5.5, 'A', 5.8], [57, 62, 72, 75], [19.3, 12.7, 20.3, None], ['Yes', 'no', None, 'Yes']])

In [6]:
health_data_frame=pd.DataFrame(health_data_table)

In [7]:
health_data_frame.head(2)

  height  weight   bmi smoker
0    5.5      57  19.3    Yes
1    5.5      62  12.7     no

In [8]:
health_data_frame.tail(3)

  height  weight   bmi smoker
1    5.5      62  12.7     no
2      A      72  20.3    NaN
3    5.8      75   NaN    Yes

In [9]:
health_data_frame.shape

(4, 4)

In [10]:
health_data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  4 non-null      object
 1   weight  4 non-null      int64
 2   bmi     3 non-null      float64
 3   smoker  3 non-null      str
dtypes: float64(1), int64(1), object(1), str(1)
memory usage: 260.0+ bytes

In [11]:
# Statistical Summary
health_data_frame.describe()

         weight        bmi
count   4.00000   3.000000
mean   66.50000  17.433333
std     8.42615   4.129568
min    57.00000  12.700000
25%    60.75000  16.000000
50%    67.00000  19.300000
75%    72.75000  19.800000
max    75.00000  20.300000

In [12]:
health_data_np_array=health_data_frame.values
print(health_data_np_array)
print(type(health_data_np_array))

[[5.5 57 19.3 'Yes']
 [5.5 62 12.7 'no']
 ['A' 72 20.3 nan]
 [5.8 75 nan 'Yes']]
<class 'numpy.ndarray'>

In [13]:
print(health_data_frame.columns)
print(type(health_data_frame.columns))

Index(['height', 'weight', 'bmi', 'smoker'], dtype='str')
<class 'pandas.Index'>

In [16]:
"""
Google Framework for Data Analysis
Ask- Hypothesis Formulate
Prepare-Clean
Process-Transform
Analyze- Analyze the date to find the answers
Share- Share the answers visually with stakeholders
Act- Plan of action
"""
health_data_frame.columns=["Height (Feet)","Weight (kg)","BMI","Is Smoker"]
health_data_frame

  Height (Feet)  Weight (kg)   BMI Is Smoker
0           5.5           57  19.3       Yes
1           5.5           62  12.7        no
2             A           72  20.3       NaN
3           5.8           75   NaN       Yes

In [17]:
health_data_frame.to_csv(
    "E:\\BongoDev\\Python-Programming\\my_saved_df.csv",
    index=False,
)

In [22]:
my_saved_df=pd.read_csv("E:\\BongoDev\\Python-Programming\\my_saved_df.csv" )
my_saved_df.head()

  Height (Feet)  Weight (kg)   BMI Is Smoker
0           5.5           57  19.3       Yes
1           5.5           62  12.7        no
2             A           72  20.3       NaN
3           5.8           75   NaN       Yes

In [26]:
df=pd.read_csv("E:\\BongoDev\\Python-Programming\\homelessness.csv")
print(type(df))
df.head()

<class 'pandas.DataFrame'>

,Unnamed: 0,region,state,individuals,family_members,state_pop
0,0,East South Central,Alabama,2570.0,864.0,4887681
1,1,Pacific,Alaska,1434.0,582.0,735139
2,2,Mountain,Arizona,7259.0,2606.0,7158024
3,3,West South Central,Arkansas,2280.0,432.0,3009733
4,4,Pacific,California,109008.0,20964.0,39461588

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      51 non-null     int64
 1   region          51 non-null     str
 2   state           51 non-null     str
 3   individuals     51 non-null     float64
 4   family_members  51 non-null     float64
 5   state_pop       51 non-null     int64
dtypes: float64(2), int64(2), str(2)
memory usage: 2.5 KB

In [29]:
df.columns

Index(['Unnamed: 0', 'region', 'state', 'individuals', 'family_members',
       'state_pop'],
      dtype='str')

In [35]:
sorted_df_by_cols=df.sort_values(
    by=["region",'state'],
    ascending=[False,True],

)
sorted_df_by_cols.head(50)

,Unnamed: 0,region,state,individuals,family_members,state_pop
3,3,West South Central,Arkansas,2280.0,432.0,3009733
18,18,West South Central,Louisiana,2540.0,519.0,4659690
36,36,West South Central,Oklahoma,2823.0,1048.0,3940235
43,43,West South Central,Texas,19199.0,6111.0,28628666
15,15,West North Central,Iowa,1711.0,1038.0,3148618
16,16,West North Central,Kansas,1443.0,773.0,2911359
23,23,West North Central,Minnesota,3993.0,3250.0,5606249
25,25,West North Central,Missouri,3776.0,2107.0,6121623
27,27,West North Central,Nebraska,1745.0,676.0,1925614
34,34,West North Central,North Dakota,467.0,75.0,758080
41,41,West North Central,South Dakota,836.0,323.0,878698
7,7,South Atlantic,Delaware,708.0,374.0,965479
8,8,South Atlantic,District of Columbia,3770.0,3134.0,701547
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
10,10,South Atlantic,Georgia,6943.0,2556.0,10511131
20,20,South Atlantic,Maryland,4914.0,2230.0,6035802
33,33,South Atlantic,North Carolina,6451.0,2817.0,10381615
40,40,South Atlantic,South Carolina,3082.0,851.0,5084156
46,46,South Atlantic,Virginia,3928.0,2047.0,8501286
48,48,South Atlantic,West Virginia,1021.0,222.0,1804291
1,1,Pacific,Alaska,1434.0,582.0,735139
4,4,Pacific,California,109008.0,20964.0,39461588
11,11,Pacific,Hawaii,4131.0,2399.0,1420593
37,37,Pacific,Oregon,11139.0,3337.0,4181886
47,47,Pacific,Washington,16424.0,5880.0,7523869
6,6,New England,Connecticut,2280.0,1696.0,3571520
19,19,New England,Maine,1450.0,1066.0,1339057
21,21,New England,Massachusetts,6811.0,13257.0,6882635
29,29,New England,New Hampshire,835.0,615.0,1353465
39,39,New England,Rhode Island,747.0,354.0,1058287
45,45,New England,Vermont,780.0,511.0,624358
2,2,Mountain,Arizona,7259.0,2606.0,7158024
5,5,Mountain,Colorado,7607.0,3250.0,5691287
12,12,Mountain,Idaho,1297.0,715.0,1750536
26,26,Mountain,Montana,983.0,422.0,1060665
28,28,Mountain,Nevada,7058.0,486.0,3027341
31,31,Mountain,New Mexico,1949.0,602.0,2092741
44,44,Mountain,Utah,1904.0,972.0,3153550
50,50,Mountain,Wyoming,434.0,205.0,577601
30,30,Mid-Atlantic,New Jersey,6048.0,3350.0,8886025
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
38,38,Mid-Atlantic,Pennsylvania,8163.0,5349.0,12800922
0,0,East South Central,Alabama,2570.0,864.0,4887681
17,17,East South Central,Kentucky,2735.0,953.0,4461153
24,24,East South Central,Mississippi,1024.0,328.0,2981020
42,42,East South Central,Tennessee,6139.0,1744.0,6771631
13,13,East North Central,Illinois,6752.0,3891.0,12723071
14,14,East North Central,Indiana,3776.0,1482.0,6695497
22,22,East North Central,Michigan,5209.0,3142.0,9984072
35,35,East North Central,Ohio,6929.0,3320.0,11676341

In [36]:
# Pandas Dataframe is a collection of series data structure(col)

individuals=df['individuals']
print(type(individuals))
print(individuals)

<class 'pandas.Series'>
0       2570.0
1       1434.0
2       7259.0
3       2280.0
4     109008.0
5       7607.0
6       2280.0
7        708.0
8       3770.0
9      21443.0
10      6943.0
11      4131.0
12      1297.0
13      6752.0
14      3776.0
15      1711.0
16      1443.0
17      2735.0
18      2540.0
19      1450.0
20      4914.0
21      6811.0
22      5209.0
23      3993.0
24      1024.0
25      3776.0
26       983.0
27      1745.0
28      7058.0
29       835.0
30      6048.0
31      1949.0
32     39827.0
33      6451.0
34       467.0
35      6929.0
36      2823.0
37     11139.0
38      8163.0
39       747.0
40      3082.0
41       836.0
42      6139.0
43     19199.0
44      1904.0
45       780.0
46      3928.0
47     16424.0
48      1021.0
49      2740.0
50       434.0
Name: individuals, dtype: float64

In [38]:
new_df=df[['region','family_members']]
new_df.head()

               region  family_members
0  East South Central           864.0
1             Pacific           582.0
2            Mountain          2606.0
3  West South Central           432.0
4             Pacific         20964.0

In [40]:
# Selecting ROws

mask=df['region']=='Mountain'
df_mountain=df[mask]
df_mountain.head()

    Unnamed: 0    region     state  individuals  family_members  state_pop
2            2  Mountain   Arizona       7259.0          2606.0    7158024
5            5  Mountain  Colorado       7607.0          3250.0    5691287
12          12  Mountain     Idaho       1297.0           715.0    1750536
26          26  Mountain   Montana        983.0           422.0    1060665
28          28  Mountain    Nevada       7058.0           486.0    3027341

In [42]:
df_gt_10k=df[df['individuals']>10000]
df_gt_10k.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop
4,4,Pacific,California,109008.0,20964.0,39461588
9,9,South Atlantic,Florida,21443.0,9587.0,21244317
32,32,Mid-Atlantic,New York,39827.0,52070.0,19530351
37,37,Pacific,Oregon,11139.0,3337.0,4181886
43,43,West South Central,Texas,19199.0,6111.0,28628666

In [45]:
is_family_lt_1k_mask=df['family_members']<10000
is_region_pacific_mask=df['region']=='Pacific'

new_df=df[is_family_lt_1k_mask & is_region_pacific_mask]
new_df.head()

   Unnamed: 0   region     state  individuals  family_members  state_pop
0           0  Pacific   Alabama       2570.0           864.0    4887681
1           1  Pacific    Alaska       1434.0           582.0     735139
2           2  Pacific   Arizona       7259.0          2606.0    7158024
3           3  Pacific  Arkansas       2280.0           432.0    3009733
5           5  Pacific  Colorado       7607.0          3250.0    5691287

In [46]:
df['total_population']=df['individuals']+df['state_pop']
df.head()

,Unnamed: 0,region,state,individuals,family_members,state_pop,total_population
0,0,Pacific,Alabama,2570.0,864.0,4887681,4890251.0
1,1,Pacific,Alaska,1434.0,582.0,735139,736573.0
2,2,Pacific,Arizona,7259.0,2606.0,7158024,7165283.0
3,3,Pacific,Arkansas,2280.0,432.0,3009733,3012013.0
4,4,Pacific,California,109008.0,20964.0,39461588,39570596.0

In [47]:
df.query(
    "family_members<10000 and region=='Pacific'",

)

,Unnamed: 0,region,state,individuals,family_members,state_pop,total_population
0,0,Pacific,Alabama,2570.0,864.0,4887681,4890251.0
1,1,Pacific,Alaska,1434.0,582.0,735139,736573.0
2,2,Pacific,Arizona,7259.0,2606.0,7158024,7165283.0
3,3,Pacific,Arkansas,2280.0,432.0,3009733,3012013.0
5,5,Pacific,Colorado,7607.0,3250.0,5691287,5698894.0
6,6,Pacific,Connecticut,2280.0,1696.0,3571520,3573800.0
7,7,Pacific,Delaware,708.0,374.0,965479,966187.0
8,8,Pacific,District of Columbia,3770.0,3134.0,701547,705317.0
9,9,Pacific,Florida,21443.0,9587.0,21244317,21265760.0
10,10,Pacific,Georgia,6943.0,2556.0,10511131,10518074.0
11,11,Pacific,Hawaii,4131.0,2399.0,1420593,1424724.0
12,12,Pacific,Idaho,1297.0,715.0,1750536,1751833.0
13,13,Pacific,Illinois,6752.0,3891.0,12723071,12729823.0
14,14,Pacific,Indiana,3776.0,1482.0,6695497,6699273.0
15,15,Pacific,Iowa,1711.0,1038.0,3148618,3150329.0
16,16,Pacific,Kansas,1443.0,773.0,2911359,2912802.0
17,17,Pacific,Kentucky,2735.0,953.0,4461153,4463888.0
18,18,Pacific,Louisiana,2540.0,519.0,4659690,4662230.0
19,19,Pacific,Maine,1450.0,1066.0,1339057,1340507.0
20,20,Pacific,Maryland,4914.0,2230.0,6035802,6040716.0
22,22,Pacific,Michigan,5209.0,3142.0,9984072,9989281.0
23,23,Pacific,Minnesota,3993.0,3250.0,5606249,5610242.0
24,24,Pacific,Mississippi,1024.0,328.0,2981020,2982044.0
25,25,Pacific,Missouri,3776.0,2107.0,6121623,6125399.0
26,26,Pacific,Montana,983.0,422.0,1060665,1061648.0
27,27,Pacific,Nebraska,1745.0,676.0,1925614,1927359.0
28,28,Pacific,Nevada,7058.0,486.0,3027341,3034399.0
29,29,Pacific,New Hampshire,835.0,615.0,1353465,1354300.0
30,30,Pacific,New Jersey,6048.0,3350.0,8886025,8892073.0
31,31,Pacific,New Mexico,1949.0,602.0,2092741,2094690.0
33,33,Pacific,North Carolina,6451.0,2817.0,10381615,10388066.0
34,34,Pacific,North Dakota,467.0,75.0,758080,758547.0
35,35,Pacific,Ohio,6929.0,3320.0,11676341,11683270.0
36,36,Pacific,Oklahoma,2823.0,1048.0,3940235,3943058.0
37,37,Pacific,Oregon,11139.0,3337.0,4181886,4193025.0
38,38,Pacific,Pennsylvania,8163.0,5349.0,12800922,12809085.0
39,39,Pacific,Rhode Island,747.0,354.0,1058287,1059034.0
40,40,Pacific,South Carolina,3082.0,851.0,5084156,5087238.0
41,41,Pacific,South Dakota,836.0,323.0,878698,879534.0
42,42,Pacific,Tennessee,6139.0,1744.0,6771631,6777770.0
43,43,Pacific,Texas,19199.0,6111.0,28628666,28647865.0
44,44,Pacific,Utah,1904.0,972.0,3153550,3155454.0
45,45,Pacific,Vermont,780.0,511.0,624358,625138.0
46,46,Pacific,Virginia,3928.0,2047.0,8501286,8505214.0
47,47,Pacific,Washington,16424.0,5880.0,7523869,7540293.0
48,48,Pacific,West Virginia,1021.0,222.0,1804291,1805312.0
49,49,Pacific,Wisconsin,2740.0,2167.0,5807406,5810146.0
50,50,Pacific,Wyoming,434.0,205.0,577601,578035.0

In [48]:
df=df.drop(columns='Unnamed: 0')
df.head()

,region,state,individuals,family_members,state_pop,total_population
0,Pacific,Alabama,2570.0,864.0,4887681,4890251.0
1,Pacific,Alaska,1434.0,582.0,735139,736573.0
2,Pacific,Arizona,7259.0,2606.0,7158024,7165283.0
3,Pacific,Arkansas,2280.0,432.0,3009733,3012013.0
4,Pacific,California,109008.0,20964.0,39461588,39570596.0

In [49]:
df['individuals'].min()

np.float64(434.0)

In [50]:
df['individuals'].max()

np.float64(109008.0)

In [51]:
df['individuals'].std()

np.float64(15991.025083231812)

In [52]:
df['individuals'].quantile(0.75)

np.float64(6781.5)

In [53]:
df.describe()

         individuals  family_members     state_pop  total_population
count      51.000000       51.000000  5.100000e+01      5.100000e+01
mean     7225.784314     3504.882353  6.405637e+06      6.412863e+06
std     15991.025083     7805.411811  7.327258e+06      7.340615e+06
min       434.000000       75.000000  5.776010e+05      5.780350e+05
25%      1446.500000      592.000000  1.777414e+06      1.778572e+06
50%      3082.000000     1482.000000  4.461153e+06      4.463888e+06
75%      6781.500000     3196.000000  7.340946e+06      7.352788e+06
max    109008.000000    52070.000000  3.946159e+07      3.957060e+07

In [54]:
# Zero Mean and Unit Variance

def normalize(col):
    mean=col.mean(),
    std=col.std()
    return (col-mean)/std

In [55]:
normalize(df['individuals'])

0    -0.291150
1    -0.362190
2     0.002077
3    -0.309285
4     6.364959
5     0.023839
6    -0.309285
7    -0.407590
8    -0.216108
9     0.889075
10   -0.017684
11   -0.193533
12   -0.370757
13   -0.029628
14   -0.215733
15   -0.344867
16   -0.361627
17   -0.280832
18   -0.293026
19   -0.361189
20   -0.144568
21   -0.025939
22   -0.126120
23   -0.202162
24   -0.387829
25   -0.215733
26   -0.390393
27   -0.342741
28   -0.010492
29   -0.399648
30   -0.073653
31   -0.329984
32    2.038720
33   -0.048451
34   -0.422661
35   -0.018559
36   -0.275328
37    0.244713
38    0.058609
39   -0.405151
40   -0.259132
41   -0.399586
42   -0.067962
43    0.748746
44   -0.332798
45   -0.403088
46   -0.206227
47    0.575211
48   -0.388017
49   -0.280519
50   -0.424725
Name: individuals, dtype: float64